[package]
name = "ar-flac-rs"
version = "0.1.0"
authors = ["Mark LeMoine <thatsgobbles@gmail.com>"]

[dependencies]
clap = "2.32.0"
glob = "0.2.11"
metaflac = "0.1.8"

[dev-dependencies]
test_util = { path = "test_util" }
tempfile = "3"
